### ISSUE TITLE
Wrong error when get undefined read cursor

### ISSUE THREAD

**Issue by Parmakli** [pusher/chatkit-android#127]
I'm trying to get read cursor for some user for some roomId, which hasn't been previously set. And I'm receiveing error (Must be subscribed to room some_id to access member's read cursors) even if I have previously checked for room subscription. Is it not better to just return null in that case? Or I'm doing something wrong?
`
     Caused by: OtherError(reason=Must be subscribed to room some_id to access member's read cursors, exception=null)
        at elements.Errors.other(errors.kt:42)
        at com.pusher.chatkit.cursors.CursorService.notSubscribedToRoom(CursorService.kt:66)
        at com.pusher.chatkit.cursors.CursorService.getReadCursor(CursorService.kt:63)
        at com.pusher.chatkit.SynchronousCurrentUser.getReadCursor(SynchronousCurrentUser.kt:56)
        at com.pusher.chatkit.CurrentUser.getReadCursor(CurrentUser.kt:61)`

**Comment by daniellevass** [comment]
Hi, I believe we fixed this issue in [1.8.](https://github.com/pusher/chatkit-android/releases/tag/1.8.1). If this is still an issue please contact support@pusher.com, and they can give you more direct help 🙂
