### ISSUE TITLE
Require ACCESS_NETWORK_STATE

### ISSUE THREAD

**Issue by KingIdee** [pusher/chatkit-android#48]
When I use ChatKit in a sample app, I always come across this error when the app could not connect to the internet. Even when I require the permission in my app, it still resurfaces.

```
2018-06-01 10:52:38.004 9218-9243/com.pusher.chatkitdemo E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.pusher.chatkitdemo, PID: 9218
    java.lang.SecurityException: ConnectivityService: Neither user 10081 nor current process has android.permission.ACCESS_NETWORK_STATE.
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.os.Parcel.readException(Parcel.java:1950)
        at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1195)
        at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:786)
        at com.pusher.platform.network.ConnectivityHelper.isConnected(ConnectivityHelper.kt:27)
        at com.pusher.platform.network.ConnectivityHelper.onConnected(ConnectivityHelper.kt:33)
        at com.pusher.platform.ErrorResolver.resolveError(ErrorResolver.kt:39)
        at com.pusher.platform.subscription.ResumingSubscription$ResumingSubscriptionState.executeSubscriptionOnce(ResumingSubscription.kt:100)
        at com.pusher.platform.subscription.ResumingSubscription$ResumingSubscriptionState.<init>(ResumingSubscription.kt:91)
        at com.pusher.platform.subscription.ResumingSubscription$OpeningSubscriptionState$3.invoke(ResumingSubscription.kt:72)
        at com.pusher.platform.subscription.ResumingSubscription$OpeningSubscriptionState$3.invoke(ResumingSubscription.kt:48)
        at com.pusher.platform.subscription.TokenProvidingSubscription$FailedSubscriptionState.<init>(TokenProvidingSubscription.kt:105)
        at com.pusher.platform.subscription.TokenProvidingSubscription$TokenProvidingState$fetchTokenAndExecuteSubscription$2.invoke(TokenProvidingSubscription.kt:86)
        at com.pusher.platform.subscription.TokenProvidingSubscription$TokenProvidingState$fetchTokenAndExecuteSubscription$2.invoke(TokenProvidingSubscription.kt:40)
        at com.pusher.chatkit.ChatkitTokenProvider$fetchTokenFromEndpoint$3.onFailure(ChatkitTokenProvider.kt:111)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:161)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by hamchapman** [comment]
Which version of the SDK are you using?

**Comment by KingIdee** [comment]
`    implementation "com.pusher:chatkit-android:0.1.0"`

**Comment by hamchapman** [comment]
If you're able to, please try updating to the latest version, `0.2.1`. This shouldn't have that problem

**Comment by hamchapman** [comment]
Did `0.2.1` fix it for you?

**Comment by hamchapman** [comment]
Closing as stale
