### ISSUE TITLE
Error Parsing Token

### ISSUE THREAD

**Issue by KingIdee** [pusher/chatkit-android#75]
I created my ChatKit server with Node.js to provide a token for my app. When I test my endpoint on postman, this is my response"
 
```
{
  "status": 200,
  "headers": {},
  "body": {
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnN0YW5jZSI6ImQ1MzBkYjE4LTIwNzMtNDdmZS04OWQxLWJhZGY0MjRmMjlhNSIsImlzcyI6ImFwaV9rZXlzLzI4NzFhMTg2LTRlMjctNDc4Zi04NTU2LTQ2NGIzZTA4NjEyZiIsImlhdCI6MTUzOTIzMzI0MCwiZXhwIjoxNTM5MzE5NjQwfQ.N9SrQOzIRNMf0acti3ENfsfzytzP2Sfm60wLG83585I",
    "expires_in": 86400,
    "token_type": "bearer"
  }
}
```

This presumes the server works perfectly.

However, the app throws an error:

```

2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: null
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:164)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.network.FlatMapFuture.get(Futures.kt:71)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.TokenProvidingSubscription.subscribe(TokenProvidingSubscription.kt:53)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.TokenProvidingSubscription.<init>(TokenProvidingSubscription.kt:43)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.TokenProvidingSubscriptionKt$createTokenProvidingStrategy$1.invoke(TokenProvidingSubscription.kt:19)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.TokenProvidingSubscriptionKt$createTokenProvidingStrategy$1.invoke(TokenProvidingSubscription.kt)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.ResumingSubscription$OpeningSubscriptionState.<init>(ResumingSubscription.kt:109)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.ResumingSubscription.<init>(ResumingSubscription.kt:39)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.ResumingSubscriptionKt$createResumingStrategy$1.invoke(ResumingSubscription.kt:18)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.subscription.ResumingSubscriptionKt$createResumingStrategy$1.invoke(ResumingSubscription.kt)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.BaseClient.subscribeResuming(BaseClient.kt:59)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.Instance.subscribeResuming(Instance.kt:72)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.Instance.subscribeResuming(Instance.kt:50)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.Instance.subscribeResuming$default(Instance.kt:49)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatManager.subscribeResuming$chatkit_core(ChatManager.kt:155)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatManager.subscribeResuming$chatkit_core$default(ChatManager.kt:154)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.users.UserSubscription.<init>(UserSubscription.kt:32)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatManager.openSubscription(ChatManager.kt:59)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatManager.connect(ChatManager.kt:55)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatManager.connect$default(ChatManager.kt:51)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.example.androidslackclone.MainActivity.connectChatKit(MainActivity.kt:76)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.example.androidslackclone.MainActivity.access$connectChatKit(MainActivity.kt:27)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.example.androidslackclone.MainActivity$getProfile$1$onSuccess$1.onSuccess(MainActivity.kt:124)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.example.androidslackclone.MainActivity$getProfile$1$onSuccess$1.onSuccess(MainActivity.kt:120)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.auth0.android.request.internal.BaseRequest.postOnSuccess(BaseRequest.java:92)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:76)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2018-10-11 05:45:03.274 3199-3370/com.example.androidslackclone W/System.err:     at java.lang.Thread.run(Thread.java:761)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err: Caused by: java.lang.NumberFormatException: null
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at java.lang.Long.parseLong(Long.java:406)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at java.lang.Long.parseLong(Long.java:485)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatkitTokenProvider.parseTokenResponse(ChatkitTokenProvider.kt:87)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatkitTokenProvider.access$parseTokenResponse(ChatkitTokenProvider.kt:23)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatkitTokenProvider$fetchTokenFromEndpoint$1$1.invoke(ChatkitTokenProvider.kt:54)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.chatkit.ChatkitTokenProvider$fetchTokenFromEndpoint$1$1.invoke(ChatkitTokenProvider.kt:23)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at com.pusher.platform.network.FuturesKt$sam$java_util_concurrent_Callable$0.call(Futures.kt)
2018-10-11 05:45:03.275 3199-3370/com.example.androidslackclone W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

My understanding of this is that it is seeing the `expires_in` value as null. This could be as a result of wrong parsing.

Please, can you look into it asap?

**Comment by hamchapman** [comment]
Judging by this line: https://github.com/pusher/chatkit-android/blob/master/chatkit-core/src/main/kotlin/com/pusher/chatkit/ChatkitTokenProvider.kt#L99

It looks like the Android client is expected the `"expires_in"` key in the JSON body to be a `string`. This is incorrect and will be fixed in a future update. 

For now, and to check that that is indeed the issue, perhaps you could try changing the JSON you return to make the value for `"expires_in"` be `"86400"`?

Let me know if that fixes it and thanks for the report 👍

**Comment by mdpye** [comment]
The library is happy with either string or number representation for the `expires_in` field.

However, I did replicate your reported errors by providing a response body of 

```
{
  "status": 200,
  "headers": {},
  "body": {
    "access_token": "a token",
    "expires_in": 86400,
    "token_type": "bearer"
  }
}
```

as you describe. 

You say that is your response as recorded by postman. Is what you pasted the literal content of your response *body*? Because the body should just be the body value from the above, the other keys are supposed to describe the whole response.

To clarify, the body of your response should be

```
{
    "access_token": "a token",
    "expires_in": 86400,
    "token_type": "bearer"
}
```
I expect if it's working correctly, that's all you'd see in postman.

**Comment by KingIdee** [comment]
Well, it turns out the error was from me. My ChatkitTokenProvider endpoint was faulty. Sorry for the false alarm.
